---
title: "Lab 00 - Hello IDS!"
author: "Juliet Shevlin"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(tibble)
```




### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Zack", "Ethan", 
           "member 3", "member 4"),
  github_username = c("mcgregors-garden", "ZackLukUoE", "EWallis08", 
                      "Milesmiller100636", "Fredrusson"), 
  colour = c("powderblue", "blue", "green", 
             "grey", "lightblue"),
  hobby = c("Hopping", "sports", "sports", 
            "golf", "golf"),
  favourite_number = c(2, 9, 4, 26, 10)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

Bar chart shows out github usernames and our favourite numbers 

